# adapted from https://github.com/andyli/HaxeCI/blob/master/.travis.yml
language: haxe

branches:
  only:
    - develop

env:
    matrix:
    - TARGET=interp
    - TARGET=cpp
    - TARGET=node

# Test with Haxe 3.2.1 and Haxe development.
haxe:
  - "3.2.1"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

install:
  # install haxelibs
  - haxelib install buddy

  # apt packages for each target
  - sudo apt-get update
  #- sh -c "if [ '$TARGET' = 'cpp' ]; then sudo apt-get install gcc-multilib g++-multilib -y; fi"
  - sudo apt-get install gcc-multilib g++-multilib -y

  # haxelib dependencies for each target
  #- sh -c "if [ '$TARGET' = 'cpp' ]; then haxelib install hxcpp; fi"
  - haxelib install hxcpp

  - haxelib install snowfall
  - haxelib run snowfall update snow

script:
  - haxe test.${TARGET}.hxml
